blank_issues_enabled: false
contact_links:
  - name: LegacyEvolved Community Discord
    url: https://discord.gg/D6hEPNYeyn
    about: If you need help, please ask for it in our Discord! You will get assistance much faster there, including help getting the project to compile.
